# src/calculator/constants.py
import math

SSP_WEEKLY_RATE = 118.75
SMP_SPP_RATE = 172.48
SSP_LOWER_EARNINGS_LIMIT = 125.0
WEEKS_IN_YEAR = 52
WORKING_DAYS_IN_WEEK = 5
SMP_SPP_RECLAIM_RATE = 0.92
RECRUITMENT_FEE_PERCENT = 20
MATERNITY_LEAVE_DURATION_WEEKS = 39

POLICY_IMPLEMENTATION_RATE = 0.03
WE_ARE_EDEN_ANNUAL_COST = 150

WORKFORCE_TOTAL_EMPLOYED = 34010000
WORKFORCE_MEN_EMPLOYED = 17510000
WORKFORCE_WOMEN_EMPLOYED = WORKFORCE_TOTAL_EMPLOYED - WORKFORCE_MEN_EMPLOYED
WORKFORCE_MEN_PERCENTAGE = WORKFORCE_MEN_EMPLOYED / WORKFORCE_TOTAL_EMPLOYED
WORKFORCE_WOMEN_PERCENTAGE = WORKFORCE_WOMEN_EMPLOYED / WORKFORCE_TOTAL_EMPLOYED

MENOPAUSE_ANNUAL_COST = 2e9 # £2 billion
MENOPAUSE_UK_PERCENTAGE = 0.3
ENDOMETRIOSIS_ANNUAL_COST = 8.2e9 # £8.2 billion
ENDOMETRIOSIS_UK_PERCENTAGE = 0.1

# WORKFORCE_WOMEN_POPULATION = 16.50e6 # 16.50 million women in employment

ENDOMETRIOSIS_COST_PER_PERSON = ENDOMETRIOSIS_ANNUAL_COST / (WORKFORCE_WOMEN_EMPLOYED * ENDOMETRIOSIS_UK_PERCENTAGE) if (WORKFORCE_WOMEN_EMPLOYED * ENDOMETRIOSIS_UK_PERCENTAGE) > 0 else 0
MENOPAUSE_COST_PER_PERSON = MENOPAUSE_ANNUAL_COST / (WORKFORCE_WOMEN_EMPLOYED * MENOPAUSE_UK_PERCENTAGE) if (WORKFORCE_WOMEN_EMPLOYED * MENOPAUSE_UK_PERCENTAGE) > 0 else 0


# Prostate cancer costs
PROSTATE_CANCER_PERCENTAGE = 0.14
WORKFORCE_CANCER_PERCENTAGE = 0.34
WORKFORCE_PROSTATE_CANCER_PERCENTAGE = WORKFORCE_CANCER_PERCENTAGE * PROSTATE_CANCER_PERCENTAGE
COST_OF_CANCER = 1.5e9

COST_OF_PROSTATE_CANCER_PER_PERSON = WORKFORCE_MEN_PERCENTAGE * COST_OF_CANCER * WORKFORCE_PROSTATE_CANCER_PERCENTAGE